version: "3"
services:
  app:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:12.7
    ports:
      - 5432:5432
    environment:
      - POSTGRES_ROOT_PASSWORD=yova
      - POSTGRES_USER=yova
      - POSTGRES_PASSWORD=yova