default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: yova
  password: yova
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: yova_development

test:
  <<: *default
  database: fv-yova_test
